export const refs = {
  heroList: document.querySelector('.js-hero-list'),
  heroSection: document.querySelector('.hero'),
  cocktailTitle: document.querySelector('.cocktail-title'),
  searchSelect: document.querySelector('#search-letter'),
  sectionSorry: document.querySelector('.js-sorry'),
  modalCocktail: document.querySelector('.modal-cocktail'),
  modalIngredient: document.querySelector('.js-modal-ingredient'),
  modal: document.querySelector('[data-modal-cocktail]'),
  listCocktail: document.querySelector('.modal-ingredients__list'),
  searchCocktails: document.querySelector('.js-search-cocktail'),
  cocktailSection: document.querySelector('.cocktail-section'),
  loadMore: document.querySelector('.load-more'),
  listFavoriteCocktails: document.querySelector('.favorite-cocktails-list'),
  listFavoriteIngredients: document.querySelector('.list-ing'),
};
